import { ServiceTicket } from './interfaces/service-tickets.interface';

// Deterministic mock dataset for PRD 3.2.1 — Service Tickets.
export const MOCK_SERVICE_TICKET: ServiceTicket[] = [
  {
    "id": "TCK2000",
    "subject": "Display screen blank",
    "machine": "VM-1042",
    "status": "In Progress",
    "raisedBy": "Neha Kulkarni",
    "raisedOn": "2026-06-01",
    "updatedOn": "2026-06-01",
    "resolvedAt": "—",
    "assignedTo": "Priya Nair",
    "escalationPriority": "High",
    "applicationType": "Network"
  },
  {
    "id": "TCK2001",
    "subject": "Cooling unit fault",
    "machine": "VM-2007",
    "status": "Escalated",
    "raisedBy": "Priya Nair",
    "raisedOn": "2026-06-29",
    "updatedOn": "2026-06-29",
    "resolvedAt": "—",
    "assignedTo": "Priya Nair",
    "escalationPriority": "Low",
    "applicationType": "Network"
  },
  {
    "id": "TCK2002",
    "subject": "Display screen blank",
    "machine": "VM-3010",
    "status": "In Progress",
    "raisedBy": "Sana Iyer",
    "raisedOn": "2026-06-17",
    "updatedOn": "2026-06-17",
    "resolvedAt": "—",
    "assignedTo": "Anita Rao",
    "escalationPriority": "High",
    "applicationType": "Payment"
  },
  {
    "id": "TCK2003",
    "subject": "Door lock jammed",
    "machine": "VM-2007",
    "status": "In Progress",
    "raisedBy": "Farhan Sheikh",
    "raisedOn": "2026-07-01",
    "updatedOn": "2026-07-01",
    "resolvedAt": "—",
    "assignedTo": "Farhan Sheikh",
    "escalationPriority": "Medium",
    "applicationType": "Hardware"
  },
  {
    "id": "TCK2004",
    "subject": "Display screen blank",
    "machine": "VM-1042",
    "status": "Resolved",
    "raisedBy": "Anita Rao",
    "raisedOn": "2026-04-24",
    "updatedOn": "2026-04-24",
    "resolvedAt": "2026-04-24",
    "assignedTo": "Sana Iyer",
    "escalationPriority": "Medium",
    "applicationType": "Network"
  },
  {
    "id": "TCK2005",
    "subject": "Network connectivity issue",
    "machine": "VM-2007",
    "status": "Resolved",
    "raisedBy": "Neha Kulkarni",
    "raisedOn": "2026-07-15",
    "updatedOn": "2026-07-15",
    "resolvedAt": "2026-07-15",
    "assignedTo": "Neha Kulkarni",
    "escalationPriority": "Critical",
    "applicationType": "Hardware"
  },
  {
    "id": "TCK2006",
    "subject": "Network connectivity issue",
    "machine": "VM-2088",
    "status": "Escalated",
    "raisedBy": "Sana Iyer",
    "raisedOn": "2026-06-11",
    "updatedOn": "2026-06-11",
    "resolvedAt": "—",
    "assignedTo": "Arjun Verma",
    "escalationPriority": "Low",
    "applicationType": "Payment"
  },
  {
    "id": "TCK2007",
    "subject": "Cooling unit fault",
    "machine": "VM-1021",
    "status": "In Progress",
    "raisedBy": "Anita Rao",
    "raisedOn": "2026-05-15",
    "updatedOn": "2026-05-15",
    "resolvedAt": "—",
    "assignedTo": "Rohit Mehta",
    "escalationPriority": "Low",
    "applicationType": "Payment"
  },
  {
    "id": "TCK2008",
    "subject": "Network connectivity issue",
    "machine": "VM-3125",
    "status": "Escalated",
    "raisedBy": "Neha Kulkarni",
    "raisedOn": "2026-07-16",
    "updatedOn": "2026-07-16",
    "resolvedAt": "—",
    "assignedTo": "Vikram Shah",
    "escalationPriority": "Medium",
    "applicationType": "Software"
  },
  {
    "id": "TCK2009",
    "subject": "Display screen blank",
    "machine": "VM-2007",
    "status": "Closed",
    "raisedBy": "Rohit Mehta",
    "raisedOn": "2026-05-21",
    "updatedOn": "2026-05-21",
    "resolvedAt": "2026-05-21",
    "assignedTo": "Farhan Sheikh",
    "escalationPriority": "Critical",
    "applicationType": "Network"
  },
  {
    "id": "TCK2010",
    "subject": "Machine not dispensing",
    "machine": "VM-1021",
    "status": "Closed",
    "raisedBy": "Farhan Sheikh",
    "raisedOn": "2026-06-15",
    "updatedOn": "2026-06-15",
    "resolvedAt": "2026-06-15",
    "assignedTo": "Rohit Mehta",
    "escalationPriority": "Critical",
    "applicationType": "Payment"
  },
  {
    "id": "TCK2011",
    "subject": "Machine not dispensing",
    "machine": "VM-3125",
    "status": "Closed",
    "raisedBy": "Farhan Sheikh",
    "raisedOn": "2026-05-10",
    "updatedOn": "2026-05-10",
    "resolvedAt": "2026-05-10",
    "assignedTo": "Farhan Sheikh",
    "escalationPriority": "Low",
    "applicationType": "Hardware"
  },
  {
    "id": "TCK2012",
    "subject": "Cooling unit fault",
    "machine": "VM-3010",
    "status": "Closed",
    "raisedBy": "Sana Iyer",
    "raisedOn": "2026-07-22",
    "updatedOn": "2026-07-22",
    "resolvedAt": "2026-07-22",
    "assignedTo": "Vikram Shah",
    "escalationPriority": "Low",
    "applicationType": "Network"
  },
  {
    "id": "TCK2013",
    "subject": "Door lock jammed",
    "machine": "VM-1042",
    "status": "Escalated",
    "raisedBy": "Anita Rao",
    "raisedOn": "2026-05-26",
    "updatedOn": "2026-05-26",
    "resolvedAt": "—",
    "assignedTo": "Farhan Sheikh",
    "escalationPriority": "High",
    "applicationType": "Hardware"
  },
  {
    "id": "TCK2014",
    "subject": "Cooling unit fault",
    "machine": "VM-1042",
    "status": "Escalated",
    "raisedBy": "Farhan Sheikh",
    "raisedOn": "2026-07-17",
    "updatedOn": "2026-07-17",
    "resolvedAt": "—",
    "assignedTo": "Neha Kulkarni",
    "escalationPriority": "Low",
    "applicationType": "Hardware"
  },
  {
    "id": "TCK2015",
    "subject": "Machine not dispensing",
    "machine": "VM-3125",
    "status": "Open",
    "raisedBy": "Farhan Sheikh",
    "raisedOn": "2026-07-22",
    "updatedOn": "2026-07-22",
    "resolvedAt": "—",
    "assignedTo": "Priya Nair",
    "escalationPriority": "High",
    "applicationType": "Network"
  },
  {
    "id": "TCK2016",
    "subject": "Network connectivity issue",
    "machine": "VM-3010",
    "status": "Open",
    "raisedBy": "Anita Rao",
    "raisedOn": "2026-05-12",
    "updatedOn": "2026-05-12",
    "resolvedAt": "—",
    "assignedTo": "Priya Nair",
    "escalationPriority": "Medium",
    "applicationType": "Payment"
  },
  {
    "id": "TCK2017",
    "subject": "Coin jam",
    "machine": "VM-1042",
    "status": "Open",
    "raisedBy": "Neha Kulkarni",
    "raisedOn": "2026-06-18",
    "updatedOn": "2026-06-18",
    "resolvedAt": "—",
    "assignedTo": "Neha Kulkarni",
    "escalationPriority": "Medium",
    "applicationType": "Network"
  },
  {
    "id": "TCK2018",
    "subject": "Display screen blank",
    "machine": "VM-2088",
    "status": "In Progress",
    "raisedBy": "Sana Iyer",
    "raisedOn": "2026-06-21",
    "updatedOn": "2026-06-21",
    "resolvedAt": "—",
    "assignedTo": "Priya Nair",
    "escalationPriority": "High",
    "applicationType": "Network"
  },
  {
    "id": "TCK2019",
    "subject": "Door lock jammed",
    "machine": "VM-2007",
    "status": "Closed",
    "raisedBy": "Anita Rao",
    "raisedOn": "2026-05-15",
    "updatedOn": "2026-05-15",
    "resolvedAt": "2026-05-15",
    "assignedTo": "Vikram Shah",
    "escalationPriority": "High",
    "applicationType": "Software"
  },
  {
    "id": "TCK2020",
    "subject": "Coin jam",
    "machine": "VM-3010",
    "status": "In Progress",
    "raisedBy": "Vikram Shah",
    "raisedOn": "2026-07-05",
    "updatedOn": "2026-07-05",
    "resolvedAt": "—",
    "assignedTo": "Anita Rao",
    "escalationPriority": "Critical",
    "applicationType": "Hardware"
  },
  {
    "id": "TCK2021",
    "subject": "Machine not dispensing",
    "machine": "VM-3125",
    "status": "In Progress",
    "raisedBy": "Priya Nair",
    "raisedOn": "2026-04-24",
    "updatedOn": "2026-04-24",
    "resolvedAt": "—",
    "assignedTo": "Farhan Sheikh",
    "escalationPriority": "Critical",
    "applicationType": "Hardware"
  },
  {
    "id": "TCK2022",
    "subject": "Network connectivity issue",
    "machine": "VM-1021",
    "status": "Open",
    "raisedBy": "Arjun Verma",
    "raisedOn": "2026-05-24",
    "updatedOn": "2026-05-24",
    "resolvedAt": "—",
    "assignedTo": "Sana Iyer",
    "escalationPriority": "High",
    "applicationType": "Payment"
  },
  {
    "id": "TCK2023",
    "subject": "Cooling unit fault",
    "machine": "VM-3010",
    "status": "Closed",
    "raisedBy": "Arjun Verma",
    "raisedOn": "2026-05-21",
    "updatedOn": "2026-05-21",
    "resolvedAt": "2026-05-21",
    "assignedTo": "Arjun Verma",
    "escalationPriority": "Critical",
    "applicationType": "Payment"
  },
  {
    "id": "TCK2024",
    "subject": "Display screen blank",
    "machine": "VM-3125",
    "status": "Closed",
    "raisedBy": "Arjun Verma",
    "raisedOn": "2026-07-13",
    "updatedOn": "2026-07-13",
    "resolvedAt": "2026-07-13",
    "assignedTo": "Priya Nair",
    "escalationPriority": "High",
    "applicationType": "Hardware"
  },
  {
    "id": "TCK2025",
    "subject": "Door lock jammed",
    "machine": "VM-3125",
    "status": "In Progress",
    "raisedBy": "Farhan Sheikh",
    "raisedOn": "2026-05-10",
    "updatedOn": "2026-05-10",
    "resolvedAt": "—",
    "assignedTo": "Arjun Verma",
    "escalationPriority": "Low",
    "applicationType": "Payment"
  }
];

export const SERVICE_TICKET_STATUSES: string[] = ["Open","In Progress","Escalated","Resolved","Closed"];
export const SERVICE_TICKET_MACHINE: string[] = ["VM-1021","VM-1042","VM-2007","VM-2088","VM-3010","VM-3125"];
export const SERVICE_TICKET_ESCALATIONPRIORITY: string[] = ["Critical","High","Low","Medium"];
export const SERVICE_TICKET_APPLICATIONTYPE: string[] = ["Hardware","Network","Payment","Software"];
