import { LedgerEntry } from './interfaces/stock-location-ledger.interface';

// Deterministic mock dataset for PRD 2.2.2.10 — Stock Location Ledger.
export const MOCK_LEDGER_ENTRY: LedgerEntry[] = [
  {
    "id": "LDG20039",
    "dateTime": "2026-06-23T20:51:00",
    "movementType": "Stock Transfer Out",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-8890",
    "stockLocation": "Gurgaon Warehouse",
    "product": "Coca-Cola 250ml",
    "previousQuantity": 236,
    "stockIn": 0,
    "stockOut": 23,
    "balance": 213
  },
  {
    "id": "LDG20038",
    "dateTime": "2026-07-16T17:14:00",
    "movementType": "Machine Refill",
    "sourceModule": "Machine Refills",
    "referenceNumber": "MAC-6558",
    "stockLocation": "Gurgaon Warehouse",
    "product": "KitKat 4-finger",
    "previousQuantity": 272,
    "stockIn": 0,
    "stockOut": 36,
    "balance": 236
  },
  {
    "id": "LDG20037",
    "dateTime": "2026-07-23T06:47:00",
    "movementType": "Return Order",
    "sourceModule": "Return Orders",
    "referenceNumber": "RET-1943",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Bisleri 500ml",
    "previousQuantity": 267,
    "stockIn": 5,
    "stockOut": 0,
    "balance": 272
  },
  {
    "id": "LDG20036",
    "dateTime": "2026-06-25T17:18:00",
    "movementType": "Stock Transfer Out",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-3123",
    "stockLocation": "Gurgaon Warehouse",
    "product": "Real Juice 200ml",
    "previousQuantity": 303,
    "stockIn": 0,
    "stockOut": 36,
    "balance": 267
  },
  {
    "id": "LDG20035",
    "dateTime": "2026-07-13T07:31:00",
    "movementType": "Stock Transfer In",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-2107",
    "stockLocation": "North Delhi Warehouse",
    "product": "Britannia Good Day",
    "previousQuantity": 298,
    "stockIn": 5,
    "stockOut": 0,
    "balance": 303
  },
  {
    "id": "LDG20034",
    "dateTime": "2026-07-12T12:31:00",
    "movementType": "Stock Transfer In",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-9534",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Oreo 50g",
    "previousQuantity": 280,
    "stockIn": 18,
    "stockOut": 0,
    "balance": 298
  },
  {
    "id": "LDG20033",
    "dateTime": "2026-06-27T16:07:00",
    "movementType": "Machine Refill",
    "sourceModule": "Machine Refills",
    "referenceNumber": "MAC-1837",
    "stockLocation": "North Delhi Warehouse",
    "product": "Real Juice 200ml",
    "previousQuantity": 315,
    "stockIn": 0,
    "stockOut": 35,
    "balance": 280
  },
  {
    "id": "LDG20032",
    "dateTime": "2026-06-30T08:33:00",
    "movementType": "Machine Refill",
    "sourceModule": "Machine Refills",
    "referenceNumber": "MAC-6102",
    "stockLocation": "Bangalore East Warehouse",
    "product": "Bisleri 500ml",
    "previousQuantity": 341,
    "stockIn": 0,
    "stockOut": 26,
    "balance": 315
  },
  {
    "id": "LDG20031",
    "dateTime": "2026-07-19T20:39:00",
    "movementType": "Purchase Receipt",
    "sourceModule": "Purchase Orders",
    "referenceNumber": "PUR-3825",
    "stockLocation": "Bangalore East Warehouse",
    "product": "Sprite 250ml",
    "previousQuantity": 313,
    "stockIn": 28,
    "stockOut": 0,
    "balance": 341
  },
  {
    "id": "LDG20030",
    "dateTime": "2026-07-04T07:47:00",
    "movementType": "Purchase Receipt",
    "sourceModule": "Purchase Orders",
    "referenceNumber": "PUR-2368",
    "stockLocation": "North Delhi Warehouse",
    "product": "Britannia Good Day",
    "previousQuantity": 277,
    "stockIn": 36,
    "stockOut": 0,
    "balance": 313
  },
  {
    "id": "LDG20029",
    "dateTime": "2026-07-20T15:26:00",
    "movementType": "Stock Transfer In",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-6883",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Lays Classic 52g",
    "previousQuantity": 251,
    "stockIn": 26,
    "stockOut": 0,
    "balance": 277
  },
  {
    "id": "LDG20028",
    "dateTime": "2026-07-01T14:25:00",
    "movementType": "Stock Audit Adjustment",
    "sourceModule": "Stock Audits",
    "referenceNumber": "STO-2616",
    "stockLocation": "North Delhi Warehouse",
    "product": "Britannia Good Day",
    "previousQuantity": 285,
    "stockIn": 0,
    "stockOut": 34,
    "balance": 251
  },
  {
    "id": "LDG20027",
    "dateTime": "2026-07-04T13:32:00",
    "movementType": "Purchase Receipt",
    "sourceModule": "Purchase Orders",
    "referenceNumber": "PUR-8445",
    "stockLocation": "North Delhi Warehouse",
    "product": "Lays Classic 52g",
    "previousQuantity": 251,
    "stockIn": 34,
    "stockOut": 0,
    "balance": 285
  },
  {
    "id": "LDG20026",
    "dateTime": "2026-06-28T08:16:00",
    "movementType": "Purchase Receipt",
    "sourceModule": "Purchase Orders",
    "referenceNumber": "PUR-1811",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Britannia Good Day",
    "previousQuantity": 216,
    "stockIn": 35,
    "stockOut": 0,
    "balance": 251
  },
  {
    "id": "LDG20025",
    "dateTime": "2026-07-03T15:40:00",
    "movementType": "Stock Transfer Out",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-4387",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Oreo 50g",
    "previousQuantity": 224,
    "stockIn": 0,
    "stockOut": 8,
    "balance": 216
  },
  {
    "id": "LDG20024",
    "dateTime": "2026-07-14T15:53:00",
    "movementType": "Stock Transfer In",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-3590",
    "stockLocation": "Bangalore East Warehouse",
    "product": "Lays Classic 52g",
    "previousQuantity": 194,
    "stockIn": 30,
    "stockOut": 0,
    "balance": 224
  },
  {
    "id": "LDG20023",
    "dateTime": "2026-07-08T11:49:00",
    "movementType": "Stock Transfer Out",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-2353",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Sprite 250ml",
    "previousQuantity": 220,
    "stockIn": 0,
    "stockOut": 26,
    "balance": 194
  },
  {
    "id": "LDG20022",
    "dateTime": "2026-07-07T11:37:00",
    "movementType": "Stock Audit Adjustment",
    "sourceModule": "Stock Audits",
    "referenceNumber": "STO-7448",
    "stockLocation": "North Delhi Warehouse",
    "product": "Coca-Cola 250ml",
    "previousQuantity": 230,
    "stockIn": 0,
    "stockOut": 10,
    "balance": 220
  },
  {
    "id": "LDG20021",
    "dateTime": "2026-07-08T09:14:00",
    "movementType": "Return Order",
    "sourceModule": "Return Orders",
    "referenceNumber": "RET-3171",
    "stockLocation": "Bangalore East Warehouse",
    "product": "Bisleri 500ml",
    "previousQuantity": 213,
    "stockIn": 17,
    "stockOut": 0,
    "balance": 230
  },
  {
    "id": "LDG20020",
    "dateTime": "2026-07-06T21:05:00",
    "movementType": "Stock Audit Adjustment",
    "sourceModule": "Stock Audits",
    "referenceNumber": "STO-5414",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Sprite 250ml",
    "previousQuantity": 224,
    "stockIn": 0,
    "stockOut": 11,
    "balance": 213
  },
  {
    "id": "LDG20019",
    "dateTime": "2026-07-04T08:20:00",
    "movementType": "Purchase Receipt",
    "sourceModule": "Purchase Orders",
    "referenceNumber": "PUR-5726",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Bisleri 500ml",
    "previousQuantity": 203,
    "stockIn": 21,
    "stockOut": 0,
    "balance": 224
  },
  {
    "id": "LDG20018",
    "dateTime": "2026-07-05T10:37:00",
    "movementType": "Return Order",
    "sourceModule": "Return Orders",
    "referenceNumber": "RET-1121",
    "stockLocation": "North Delhi Warehouse",
    "product": "Bisleri 500ml",
    "previousQuantity": 199,
    "stockIn": 4,
    "stockOut": 0,
    "balance": 203
  },
  {
    "id": "LDG20017",
    "dateTime": "2026-06-26T16:06:00",
    "movementType": "Stock Transfer In",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-8707",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Sprite 250ml",
    "previousQuantity": 177,
    "stockIn": 22,
    "stockOut": 0,
    "balance": 199
  },
  {
    "id": "LDG20016",
    "dateTime": "2026-06-27T21:47:00",
    "movementType": "Stock Transfer In",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-4371",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Britannia Good Day",
    "previousQuantity": 166,
    "stockIn": 11,
    "stockOut": 0,
    "balance": 177
  },
  {
    "id": "LDG20015",
    "dateTime": "2026-07-08T12:30:00",
    "movementType": "Stock Audit Adjustment",
    "sourceModule": "Stock Audits",
    "referenceNumber": "STO-2655",
    "stockLocation": "Gurgaon Warehouse",
    "product": "KitKat 4-finger",
    "previousQuantity": 180,
    "stockIn": 0,
    "stockOut": 14,
    "balance": 166
  },
  {
    "id": "LDG20014",
    "dateTime": "2026-07-01T08:36:00",
    "movementType": "Stock Transfer Out",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-3909",
    "stockLocation": "North Delhi Warehouse",
    "product": "Lays Classic 52g",
    "previousQuantity": 195,
    "stockIn": 0,
    "stockOut": 15,
    "balance": 180
  },
  {
    "id": "LDG20013",
    "dateTime": "2026-07-22T16:09:00",
    "movementType": "Purchase Receipt",
    "sourceModule": "Purchase Orders",
    "referenceNumber": "PUR-4353",
    "stockLocation": "North Delhi Warehouse",
    "product": "Bisleri 500ml",
    "previousQuantity": 156,
    "stockIn": 39,
    "stockOut": 0,
    "balance": 195
  },
  {
    "id": "LDG20012",
    "dateTime": "2026-06-23T13:10:00",
    "movementType": "Stock Transfer Out",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-4543",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Bisleri 500ml",
    "previousQuantity": 169,
    "stockIn": 0,
    "stockOut": 13,
    "balance": 156
  },
  {
    "id": "LDG20011",
    "dateTime": "2026-07-16T06:52:00",
    "movementType": "Return Order",
    "sourceModule": "Return Orders",
    "referenceNumber": "RET-6106",
    "stockLocation": "North Delhi Warehouse",
    "product": "Oreo 50g",
    "previousQuantity": 141,
    "stockIn": 28,
    "stockOut": 0,
    "balance": 169
  },
  {
    "id": "LDG20010",
    "dateTime": "2026-07-10T11:21:00",
    "movementType": "Stock Transfer Out",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-9919",
    "stockLocation": "Bangalore East Warehouse",
    "product": "Oreo 50g",
    "previousQuantity": 163,
    "stockIn": 0,
    "stockOut": 22,
    "balance": 141
  },
  {
    "id": "LDG20009",
    "dateTime": "2026-07-12T17:28:00",
    "movementType": "Stock Audit Adjustment",
    "sourceModule": "Stock Audits",
    "referenceNumber": "STO-2259",
    "stockLocation": "Gurgaon Warehouse",
    "product": "Lays Classic 52g",
    "previousQuantity": 176,
    "stockIn": 0,
    "stockOut": 13,
    "balance": 163
  },
  {
    "id": "LDG20008",
    "dateTime": "2026-07-14T09:48:00",
    "movementType": "Stock Transfer Out",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-4416",
    "stockLocation": "Gurgaon Warehouse",
    "product": "Coca-Cola 250ml",
    "previousQuantity": 184,
    "stockIn": 0,
    "stockOut": 8,
    "balance": 176
  },
  {
    "id": "LDG20007",
    "dateTime": "2026-07-23T09:25:00",
    "movementType": "Stock Audit Adjustment",
    "sourceModule": "Stock Audits",
    "referenceNumber": "STO-9474",
    "stockLocation": "Gurgaon Warehouse",
    "product": "KitKat 4-finger",
    "previousQuantity": 210,
    "stockIn": 0,
    "stockOut": 26,
    "balance": 184
  },
  {
    "id": "LDG20006",
    "dateTime": "2026-07-01T20:39:00",
    "movementType": "Purchase Receipt",
    "sourceModule": "Purchase Orders",
    "referenceNumber": "PUR-5806",
    "stockLocation": "Gurgaon Warehouse",
    "product": "Bisleri 500ml",
    "previousQuantity": 182,
    "stockIn": 28,
    "stockOut": 0,
    "balance": 210
  },
  {
    "id": "LDG20005",
    "dateTime": "2026-07-22T13:12:00",
    "movementType": "Return Order",
    "sourceModule": "Return Orders",
    "referenceNumber": "RET-5249",
    "stockLocation": "Bangalore East Warehouse",
    "product": "Britannia Good Day",
    "previousQuantity": 157,
    "stockIn": 25,
    "stockOut": 0,
    "balance": 182
  },
  {
    "id": "LDG20004",
    "dateTime": "2026-06-23T14:46:00",
    "movementType": "Stock Transfer In",
    "sourceModule": "Stock Transfers",
    "referenceNumber": "STO-4567",
    "stockLocation": "Pune Hinjewadi Warehouse",
    "product": "Sprite 250ml",
    "previousQuantity": 132,
    "stockIn": 25,
    "stockOut": 0,
    "balance": 157
  },
  {
    "id": "LDG20003",
    "dateTime": "2026-06-24T08:43:00",
    "movementType": "Purchase Receipt",
    "sourceModule": "Purchase Orders",
    "referenceNumber": "PUR-3402",
    "stockLocation": "Bangalore East Warehouse",
    "product": "Lays Classic 52g",
    "previousQuantity": 122,
    "stockIn": 10,
    "stockOut": 0,
    "balance": 132
  },
  {
    "id": "LDG20002",
    "dateTime": "2026-07-23T09:12:00",
    "movementType": "Machine Refill",
    "sourceModule": "Machine Refills",
    "referenceNumber": "MAC-6531",
    "stockLocation": "Gurgaon Warehouse",
    "product": "Sprite 250ml",
    "previousQuantity": 153,
    "stockIn": 0,
    "stockOut": 31,
    "balance": 122
  },
  {
    "id": "LDG20001",
    "dateTime": "2026-07-14T09:40:00",
    "movementType": "Stock Audit Adjustment",
    "sourceModule": "Stock Audits",
    "referenceNumber": "STO-9603",
    "stockLocation": "Bangalore East Warehouse",
    "product": "Coca-Cola 250ml",
    "previousQuantity": 163,
    "stockIn": 0,
    "stockOut": 10,
    "balance": 153
  },
  {
    "id": "LDG20000",
    "dateTime": "2026-07-11T08:25:00",
    "movementType": "Stock Audit Adjustment",
    "sourceModule": "Stock Audits",
    "referenceNumber": "STO-1306",
    "stockLocation": "North Delhi Warehouse",
    "product": "Coca-Cola 250ml",
    "previousQuantity": 175,
    "stockIn": 0,
    "stockOut": 12,
    "balance": 163
  }
];

export const LEDGER_ENTRY_MOVEMENTTYPE: string[] = ["Machine Refill","Purchase Receipt","Return Order","Stock Audit Adjustment","Stock Transfer In","Stock Transfer Out"];
export const LEDGER_ENTRY_SOURCEMODULE: string[] = ["Machine Refills","Purchase Orders","Return Orders","Stock Audits","Stock Transfers"];
